Revert "adb: add transport benchmark."
This reverts commit 97b660f364bf8f8b808995142a0c181026c0bcce [formerly d78f59ca53746b9ffa5e44dd5f0ca636ce4012d4].

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293

Former-commit-id: 2ef56a1174be8944e3c10ca5a2520f127a890b3b